INSERT INTO `user` (id, username, password, role) VALUES ('1', 'root', '1234', 'admin');
INSERT INTO `user` (id, username, password, role) VALUES ('2', 'user', '1234', 'user');
INSERT INTO `user` (id, username, password, role) VALUES ('3', 'user1', '1234', 'user');
INSERT INTO `user` (id, username, password, role) VALUES ('4', 'user2', '1234', 'user');
INSERT INTO `user` (id, username, password, role) VALUES ('5', 'user3', '1234', 'user');
INSERT INTO `user` (id, username, password, role) VALUES ('6', 'user4', '1234', 'user');
INSERT INTO `user` (id, username, password, role) VALUES ('7', '测试', '1234', 'user');
INSERT INTO `user` (id, username, password, role) VALUES ('8', 'faker1', '1234', 'user');
INSERT INTO `helloUser` (id, username, password, role) VALUES ('1', 'faker1', '1234', 'user');
INSERT INTO `file` (id,name) VALUES ('1','file1');
INSERT INTO `file` (id,name) VALUES ('2','file2');
COMMIT;